apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clustergate-backups
  labels:
    app: clustergate
    component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
